config/routes.rb
Rails.application.routes.draw do
  root "links#index"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :links, only: [:index, :create, :show, :update]

  namespace :api do
    namespace :v1 do
      resources :links, only: [:update], defaults: { format: 'json' }
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  validates :url, :url => true
  validates :title, presence: true
  enum read_status: ["Unread", "Read"]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links
  validates :email, presence: true, uniqueness: true
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  protect_from_forgery with: :null_session
  respond_to :json

  def update
    if current_user.links.include?(Link.find(params[:id]))
      respond_with Link.update(params[:id], link_params)
    else
      respond_with status: :unauthorized
    end
  end

  private

    def link_params
      params.require(:link).permit(:read_status)
    end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper_method :current_user, :authenticate

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate
    redirect_to login_path if !current_user
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  protect_from_forgery with: :exception
  before_action :authenticate

  def index
    @links = current_user.links
  end

  def create
    link = Link.new(link_params)
    if link.save
      current_user.links << link
      flash[:notice] = ["Link Successfully Created!"]
      redirect_to links_path
    else
      flash[:errors] = link.errors.full_messages
      redirect_to links_path
    end
  end

  def show
    @link = Link.find(params[:id])
  end

  def update
    link = Link.update(params[:id], link_params)
    if link.valid?
      flash[:notice] = ["Link Successfully Updated!"]
      redirect_to links_path
    else
      flash[:errors] = link.errors.full_messages
      redirect_to "/links/#{params[:id]}"
    end
  end

  private

    def link_params
      params.require(:link).permit(:url, :title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery with: :exception
  def new
  end

  def create
    if valid_user?
      session[:user_id] = @user.id
      redirect_to links_path
    else
      flash.now[:errors] = "Invalid login"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end

  private

    def session_params
      params.require(:session).permit(:email, :password)
    end

    def valid_user?
      @user = User.find_by(email: session_params[:email])
      @user && @user.authenticate(session_params[:password])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery with: :exception
  def new
  end

  def create
    if params[:user][:confirmation] == params[:user][:password]
      @user = User.new(user_params)
      create_user
    else
      flash.now[:errors] = ["Confirmation does not match password"]
      render :new
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password)
    end

    def create_user
      if @user.save
        session[:user_id] = @user.id
        redirect_to links_path
      else
        flash.now[:errors] = @user.errors.full_messages
        render :new
      end
    end
end

app/helpers/api/v1/links_helper.rb
module Api::V1::LinksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MockAssessment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/links/index.html.erb
<% if flash[:notice] %>
  <div class="notice">
    <% flash[:notice].each do |message| %>
      <%= message %>
    <% end %>
  </div>
<% end %>

<div class="well">
  <div class="btn btn-default btn-sm active" role="button">
    <%= link_to "Sign Out", logout_path, method: :delete %>
  </div>

  <h2>Add A New Link</h2>
  <% if flash[:errors] %>
    <div class="errors">
      <% flash[:errors].each do |message| %>
        <%= message %>
      <% end %>
    </div>
  <% end %>

  <%= form_for :link, url: '/links' do |f| %>
    <div class="form-inline">
      <div class="form-group">
        <%= f.label :url %>:
        <%= f.text_field :url %><br />
      </div>

      <div class="form-group">
        <%= f.label :title %>:
        <%= f.text_field :title %><br />
      </div>

      <%= f.submit "Create Link"%>
    </div>
  <% end %>

  <div class="filters">
    <h3>Filter Links By Status</h3>
    <select class="input-sm" id="filter-status">
      <option value="all">Show All</option>
      <option value="read">Read Status</option>
      <option value="unread">Unread Status</option>
    </select>

    <h3>Search By Term</h3>
    <input id="search-terms" type="text" class="form-control input-md" placeholder="Search is case Sensistive">
  </div>
</div>

<% unless @links.nil? %>
  <% @links.each do |link| %>
    <div class="links <%= link.read_status %>" id="link<%= link.id %>">
      <h3 class="link-title">Title: <%= link.title %><h3>
      <h5 class="link-url">URL: <a href="<%= link.url %>"><%= link.url %></a></h5>
      <% if link.read_status == "Read" %>
        <button class='btn btn-default btn-sm' value="Unread">Mark as Unread</button>
      <% else %>
        <button class="btn btn-default btn-sm" value="Read">Mark as Read</button>
      <% end %>
    <span class="btn btn-default btn-sm">
      <%= link_to "Edit Link", link_path(link) %>
    </span>
    </div>
  <% end %>
<% end %>

app/views/links/show.html.erb
<div class="well">
  <div class="btn btn-default btn-sm active" role="button">
    <%= link_to "Sign Out", logout_path, method: :delete %>
  </div>
  <div class="btn btn-default btn-sm active" role="button">
    <%= link_to "Index", links_path %>
  </div>

  <h2>Add A New Link</h2>
  <% if flash[:errors] %>
    <div class="errors">
      <% flash[:errors].each do |message| %>
        <%= message %>
      <% end %>
    </div>
  <% end %>
  <%= form_for @link, method: "PUT" do |f| %>
    <div class="form-inline">
      <div class="form-group">
        <%= f.label :url %>:
        <%= f.text_field :url %><br />
      </div>

      <div class="form-group">
        <%= f.label :title %>:
        <%= f.text_field :title %><br />
      </div>

      <%= f.submit "Update Link"%>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="well">
  <div class="btn btn-default btn-sm active" role="button">
    <%= link_to "Login", login_path %>
  </div>
  
  <h1>Create a new account</h1>

  <% if flash[:errors] %>
    <div class="errors">
    <% flash[:errors].each do |message| %>
      <%= message %>
    <% end %>
    </div>
  <% end %>

  <%= form_for(:user, url: users_path) do |f| %>
    <div class="form-inline">
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email %> <br>
      </div>

      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password %> <br>
      </div>

      <div class="form-group">
        <%= f.label :confirmation %>
        <%= f.password_field :confirmation %> <br>
      </div>

      <%= f.submit "Create Account" %>
    </div>
  <% end %>
</div>